server {
    listen 8000;
    server_name localhost;
    root /var/www/html/public;
    index index.php;

    # Все запросы направляем в index.php (точка входа Laravel)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Передаем PHP-скрипты в PHP-FPM
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000; # PHP-FPM слушает на этом порту внутри контейнера
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Запрещаем доступ к .htaccess и другим скрытым файлам
    location ~ /\.ht {
        deny all;
    }
}
